language: java
jdk:
  - openjdk11

sudo: required
services:
  - docker

install:
  - ./gradlew build -x check

jobs:
  include:
    - stage: app
      env: [ NAME=app ]
      script: ./gradlew :app:check

    - stage: plugins
      env: [ NAME=plugins ]
      script: ./gradlew check -x :app:check
