version: 2
executorType: machine
jobs:
  build:
    steps:
      - checkout

      - run: ./gradlew check

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
