# Liiklus config defaults
storage:
  positions:
    type: DYNAMODB

  records:
    type: KAFKA


# Spring Boot config
spring:
  jmx:
    enabled: false

  cache:
    type: NONE

endpoints:
  prometheus:
    sensitive: false