# Liiklus config defaults
storage:
  positions:
    type: DYNAMODB

  records:
    type: KAFKA


# Spring Boot config
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,prometheus

endpoints:
  prometheus:
    sensitive: false

server.port: -1

armeria:
  ports:
    - port: ${armeria.port:8080}
      protocol: HTTP
  graceful-shutdown-quiet-period-millis: 100
  graceful-shutdown-timeout-millis: 200