# Liiklus config defaults
storage:
  positions:
    type: DYNAMODB

  records:
    type: KAFKA


# Spring Boot config
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,prometheus